### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by iBobik** [tg44/heptapod#15]
This happened when I installed it:

```
?1 ~ $ brew tap tg44/heptapod
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated Homebrew from 3.4.9 (b4f7dbcc2) to 3.4.10 (bb3d97030).
Updated 4 taps (homebrew/cask-versions, homebrew/core, homebrew/cask and aws/tap).
==> New Formulae
fclones                           libtpms                           vsce
==> Updated Formulae
Updated 153 formulae.
==> Updated Casks
Updated 89 casks.


==> Homebrew was updated to version 3.4.10
The changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/3.4.10
==> Tapping tg44/heptapod
Cloning into '/usr/local/Homebrew/Library/Taps/tg44/homebrew-heptapod'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 27 (delta 9), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (27/27), done.
Resolving deltas: 100% (9/9), done.
Tapped 1 formula (12 files, 9.6KB).
~ $ brew install heptapod
==> Downloading https://github.com/tg44/heptapod/releases/download/v0.1.7/heptapod_0.1.7_Darwin_x86_
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/41
######################################################################## 100.0%
==> Installing heptapod from tg44/heptapod
==> Caveats
Start with `heptapod -h`!
==> Summary
🍺  /usr/local/Cellar/heptapod/0.1.7: 25 files, 3.7MB, built in 3 seconds
==> Running `brew cleanup heptapod`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
~ $ heptapod -h
NAME:
   heptapod - Fine-tune your TimeMachine excludes!

USAGE:
   heptapod [global options] command [command options] [arguments...]

COMMANDS:
   rules            rule related functions
   run              run the exclude detection, and also exclude the dirs
   timeMachine, tm  timeMachine related functions
   version, v       version info
   help, h          Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --bufferSize value, -b value, --buffer value  number of elements buffered, can cause deadlocks (default: 2048)
   --logDir value, --ld value                    the directory where excluded dirs logged for reliable prune/uninstall (default: "~/.heptapod/logs")
   --parallelism value, -p value, --par value    number of workers where the code is multithreaded (default: 4)
   --rules value, -r value                       the directory containing rule yamls (default: "~/.heptapod/rules")
   --verbose value, -v value                     prints out performance logs (and other logs in general) (0-4) (default: 0)
   --help, -h                                    show help (default: false)
~ $ mkdir -p ~/.heptapod/rules
cp -R $(brew --prefix heptapod)/rules ~/.heptapod
~ $ heptapod rules ls -a
Enabled rules:
                      PATH                      |        NAME        |     TYPE     | SEARCH | IGNORE  
------------------------------------------------+--------------------+--------------+--------+---------
  /Users/Bobik/.heptapod/rules/bower.yaml       | bower              | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/carthage.yaml    | carthage           | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/cocoa-pods.yaml  | CocoaPods          | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/dart.yaml        | dart               | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/go.yaml          | go                 | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/gradle-kt.yaml   | gradle-kotlin      | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/gradle.yaml      | gradle             | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/haskell.yaml     | haskell            | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/maven.yaml       | maven              | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/node.yaml        | node               | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/osx.yaml         | node-multi         | list         |        |         
  /Users/Bobik/.heptapod/rules/osx.yaml         | node-multi/library | global       |        |         
  /Users/Bobik/.heptapod/rules/php.yaml         | php                | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/python-pip.yaml  | python-pip         | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/python-pypi.yaml | python-pypi        | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/python-tox.yaml  | python-tox         | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/python-venv.yaml | python-venv        | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/ruby.yaml        | ruby               | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/rust.yaml        | rust               | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/scala-sbt.yaml   | scala-sbt          | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/swift.yaml       | swift              | file-trigger | ~      |         
  /Users/Bobik/.heptapod/rules/vagrant.yaml     | vagrant            | file-trigger | ~      |         
Disabled rules:
                  PATH                  |         NAME         |  TYPE  | SEARCH | IGNORE  
----------------------------------------+----------------------+--------+--------+---------
  /Users/Bobik/.heptapod/rules/osx.yaml | node-multi/downloads | global |        |         
  /Users/Bobik/.heptapod/rules/osx.yaml | node-multi/trash     | global |        |         
Errors:
  NONPARSEABLE FILES  
----------------------
Type parse errors:
  PATH | NAME | TYPE  
-------+------+-------
~ $ heptapod -v 1 run -d
panic: send on closed channel

goroutine 19 [running]:
github.com/tg44/heptapod/pkg/walker.worker(0x0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/heptapod/heptapod/pkg/walker/walker.go:69 +0x105
created by github.com/tg44/heptapod/pkg/walker.Run
	/home/runner/work/heptapod/heptapod/pkg/walker/walker.go:43 +0x29b
```

**Comment by tg44** [comment]
If you try this again, the error is reproducible? It happened to me only once, and I couldn't reproduce it, but this is some weird race condition (I tried to fix it at some point, but I had no idea if it worked or not bcs it was sporadic before).

What happens if you run `heptapod -p 1 -v 1 run -d`?

**Comment by iBobik** [comment]
Aha, second try of `heptapod -v 1 run -d` works.

**Comment by iBobik** [comment]
Then tried this:
```
~ $ heptapod -p 1 -v 1 run -d
2022/05/02 16:17:35 walker run took 1.647915ms
-----
```

**Comment by tg44** [comment]
Yapp, this is a race condition at the walker, and in most cases, it works without an error.

If a golang pro comes near to the project I will definitely ask them how we can solve this. Until then I can't help just ask anybody to run the command again bcs this happening by chance.
